name: Trigger auto deployment for panda-manager-backend

on:
  push:
    branches:
      [ main ]
      
  # Allow manual trigger 
  workflow_dispatch:

env:
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  PROJECT_ID: panda-manager-429621
  GAR_LOCATION: europe-southwest1
  REPOSITORY: panda-manager
  SERVICE: proxy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: GCP Login
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push image
        run: |
          docker build . --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

  gcp-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
          
      - name: GCP Login
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: backend
          region: ${{ env.GAR_LOCATION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          env_vars: |-
            APP_URL=${{ vars.APP_URL }}
            APP_PORT=${{ vars.APP_PORT }}
            OTP_MAIL_HOST=${{ vars.OTP_MAIL_HOST }}
            OTP_MAIL_PORT=${{ vars.OTP_MAIL_PORT }}
            NODE_ENV=production
            REDIS_HOST=${{ vars.REDIS_HOST }}
            REDIS_PORT=${{ vars.REDIS_PORT }}
            BACKEND_URL_GCP=${{ vars.BACKEND_URL_GCP }}
            BACKEND_URL_AZURE=${{ vars.BACKEND_URL_AZURE }}
          secrets: |-
            ACCESS_TOKEN_SECRET=access-token-secret:latest
            OTP_MAIL_USER=otp-mail-user:latest
            OTP_MAIL_PASSWORD=otp-mail-password:latest
            REDIS_USER=redis-user:latest
            REDIS_PASSWORD=redis-password:latest
