name: Trigger auto deployment for panda-manager-proxy

on:
  push:
    branches:
      [ main ]
      
  # Allow manual trigger 
  workflow_dispatch:

env:
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  PROJECT_ID: panda-manager-429621
  GAR_LOCATION: europe-southwest1
  REPOSITORY: panda-manager
  SERVICE: proxy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: GCP Login
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push image
        run: |
          docker build . --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
  
  azure-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build

    steps:
      - name: GCP Login
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PROXY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PROXY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PROXY_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: PandaManager
          containerAppName: proxy
          registryUrl: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          registryUsername: oauth2accesstoken
          registryPassword: ${{ steps.auth.outputs.access_token }}
          imageToDeploy: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          environmentVariables: "APP_URL=${{ vars.APP_URL }} APP_PORT=${{ vars.APP_PORT }} ACCESS_TOKEN_SECRET=secretref:access-token-secret OTP_MAIL_USER=secretref:otp-mail-user OTP_MAIL_PASSWORD=secretref:otp-mail-password REDIS_URL=secretref:redis-url AZURE_BACKEND_URL=${{ vars.AZURE_BACKEND_URL }} GCP_BACKEND_URL=${{ vars.GCP_BACKEND_URL }} NODE_ENV=production"
